server:
  port: 7070


spring:
  datasource:
    username: root
    password: 121518
    url: jdbc:mysql://localhost:3306/tracking?useUnicode=true&characterEncoding=UTF-8&useSSL=false&amp&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: com/ruixun/tracking/mapper/*.xml
  #该配置替换在sql-config-map中的typeAliases配置
  type-aliases-package: com.ruixun.tracking.entity
  #  configuration:
  #    log-impl:org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: com/ruixun/tracking/mapper/*.xml
  type-aliases-package: com.ruixun.tracking.entity



logging:
  level:
    com.ruixun.tracking_system.dao: DEBUG





